-- MySQL Script generated by MySQL Workbench
-- mié 22 abr 2020 12:44:53 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema epicwars
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema epicwars
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `epicwars` DEFAULT CHARACTER SET utf8 ;
USE `epicwars` ;

-- -----------------------------------------------------
-- Table `epicwars`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epicwars`.`user` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epicwars`.`user_character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epicwars`.`user_character` (
  `id_character` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `level` INT NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_character`, `username`),
  INDEX `fk_user_personaje_user_idx` (`username` ASC),
  CONSTRAINT `fk_user_personaje_user`
    FOREIGN KEY (`username`)
    REFERENCES `epicwars`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epicwars`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epicwars`.`history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `challenger` VARCHAR(45) NOT NULL,
  `challenged` VARCHAR(45) NOT NULL,
  `victory` TINYINT(1) NULL,
  `detail` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`, `challenger`, `challenged`),
  INDEX `fk_history_user1_idx` (`challenger` ASC),
  INDEX `fk_history_user2_idx` (`challenged` ASC),
  CONSTRAINT `fk_history_user1`
    FOREIGN KEY (`challenger`)
    REFERENCES `epicwars`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_history_user2`
    FOREIGN KEY (`challenged`)
    REFERENCES `epicwars`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
